%% Make a model of a peristaltic wave
close all
clear all

addpath(genpath('/Users/npmitchell/Dropbox/Soft_Matter/UCSB/gut_morphogenesis/gut_matlab/'))
outdir = '/Users/npmitchell/Dropbox/Documents/Fellowships/postdoc/faculty_applications_2022/figures/peristaltic_tube/';
if ~exist(outdir, 'dir')
    mkdir(outdir)
end

tt = linspace(0, 2*pi, 100) ;
z0 = linspace(-pi, pi, 100) ;
nU = length(z0) ;
nV = length(tt) ;

[tg, zg] = meshgrid(tt, z0) ;

rr = 1.5 -  exp(-zg(:).^2 / 2) ;
xyz = [zg(:), rr .* cos(tg(:)), rr .* sin(tg(:)) ]; 

uv = [zg(:), tg(:)] ;
FF = defineFacesRectilinearGrid(uv, nU, nV) ;

% active stress field
zall = zg(:) ;
ss = exp(-zall.^2 / 2) ;
modx = find(xyz(:, 1) > 0) ;
thresx = 0.75 ;
ss(modx) = exp(-(zall(modx) - thresx).^2 / 2).^5 ;
modx2 = find(xyz(:, 1) > 0 & xyz(:, 1) < thresx) ;
ss(modx2) = 1 ;

%% Plot it
clf 
h = trisurf(triangulation(FF, xyz), 'edgecolor', 'none', ...
    'facevertexcdata', -ss) ;
axis equal

cmap = flipud(bam)  ;
cmap = cmap(1:180,:) ;
colormap(cmap)
% colormap(flipud(othercolor('Mgrayyellowtones', 256))) ;
% cmap = interpolate_3color_cmap(linspace(0, 1, 256) , [1,0.5,1], 0.5 * [1,1,1], [0.5, 1, 0.5]) ;
% colormap(cmap) ;
axis off
colorbar
caxis([-1.5, 0.25])

set(gcf, 'color', 'w')

shading interp
% lightangle(-45,30)
camlight
h.FaceLighting = 'gouraud';
 h.AmbientStrength = 0.4;
 h.DiffuseStrength = 0.8;
 h.SpecularStrength = 0.05;
 h.SpecularExponent = 10;
%  h.BackFaceLighting = 'unlit';

saveas(gcf, fullfile(outdir, 'peristalsis_tube_v2.png'))

%%
% 
% names = {
% 'MCMYKcolors', 'MIndexed45', 'Mdarkterrain',    ...
% 'MHTML', '     MIndexed46', 'Mdeepseacolors', ...
% 'MIndexed1', ' MIndexed47', 'Mfallcolors',  ...
% 'MIndexed10', 'MIndexed48', 'Mfruitpunchcolors', ...
% 'MIndexed11', 'MIndexed49', 'Mfuchsiatones', ...    
% 'MIndexed12', 'MIndexed5', ' Mgeologicages', ...    
% 'MIndexed13', 'MIndexed50', 'Mgraytones', ...
% 'MIndexed14', 'MIndexed51', 'Mgrayyellowtones', ... 
% 'MIndexed15', 'MIndexed52', 'Mgreenbrownterrain', ...
% 'MIndexed16', 'MIndexed53', 'Mgreenpinktones', ...  
% 'MIndexed17', 'MIndexed54', 'Mhypsometrictints', ...
% 'MIndexed18', 'MIndexed55', 'Mislandcolors', ...    
% 'MIndexed19', 'MIndexed56', 'Mlakecolors', ...
% 'MIndexed2', 'MIndexed57', 'Mlegacy', ...
% 'MIndexed20', 'MIndexed58', 'Mlighttemperaturemap', ...
% 'MIndexed21', 'MIndexed59', 'Mlightterrain', ...    
% 'MIndexed22', 'MIndexed6', ' Mmintcolors', ...
% 'MIndexed23', 'MIndexed60', 'Mneoncolors', ...
% 'MIndexed24', 'MIndexed61', 'Mpastel', ...
% 'MIndexed25', 'MIndexed62', 'Mpearlcolors', ...
% 'MIndexed26', 'MIndexed7', ' Mpigeontones', ...
% 'MIndexed27', 'MIndexed8', ' Mplumcolors', ...
% 'MIndexed28', 'MIndexed9', ' Mrainbow', ...
% 'MIndexed29', 'Malpinecolors', 'Mredbluetones', ...    
% 'MIndexed3', ' Maquamarine', 'Mredgreensplit', ...   
% 'MIndexed30', 'Marmycolors', 'Mrosecolors', ...
% 'MIndexed31', 'Matlanticcolors', 'Mrusttones', ...
% 'MIndexed32', 'Matoms', 'Msandyterrain', ...    
% 'MIndexed33', 'Mauroracolors', 'Msiennatones', ...    
% 'MIndexed34', 'Mavocadocolors', 'Msolarcolors', ...     
% 'MIndexed35', 'Mbeachcolors', 'Msouthwestcolors', ...
% 'MIndexed36', 'Mblackbodyspectrum', 'Mstarrynightcolors', ...
% 'MIndexed37', 'Mbluegreenyellow', 'Msunsetcolors', ...   
% 'MIndexed38', 'Mbrasstones', 'Mtemperaturemap', ...
% 'MIndexed39', 'Mbrightbands', 'Mthermometercolors', ...  
% 'MIndexed4', ' Mbrowncyantones', 'Mvalentinetones', ...  
% 'MIndexed40', 'Mcandycolors', 'Mvisiblespectrum', ... 
% 'MIndexed41', 'Mcherrytones', 'Mwatermeloncolors', ...
% 'MIndexed42', 'Mcoffeetones', 'Mwebsafe', ...
% 'MIndexed43', 'Mdarkbands', ...
% 'MIndexed44', 'Mdarkrainbow'} ;
% 
% inds = [ 9, 24, 27, 39, 45, 48, 71, 72, 96, 99, 110] 
% 
% for ni = 1:length(names)
%     cmap_name = names{ni} ;
%     cmap = othercolor(cmap_name, 256) ;
%     colormap(flipud(cmap))
%     title(['i = ' num2str(ni)])
%     pause(0.5)
% end
